from yacs.config import CfgNode as CN

_C = CN()

_C.DATASETS = CN()
_C.DATASETS.ROOT_DIR = '../data/PIPAL(processed)'
_C.DATASETS.NUM_WORKERS = 4
_C.DATASETS.BATCH_SIZE = 4
_C.DATASETS.IMG_SIZE = (192, 192)

_C.TRAIN = CN()

_C.TRAIN.PHASE = 1

_C.TRAIN.START_EPOCH = 0
_C.TRAIN.NUM_EPOCHS = 5

_C.TRAIN.WEIGHT_DIR = ''

_C.TRAIN.RESUME = CN()
_C.TRAIN.RESUME.NET_D = ''
_C.TRAIN.RESUME.NET_G = ''

_C.TRAIN.LEARNING_RATE = CN()
_C.TRAIN.LEARNING_RATE.NET_D = 1e-5
_C.TRAIN.LEARNING_RATE.NET_G = 5e-5

_C.TRAIN.CRITERION_WEIGHT = CN()
_C.TRAIN.CRITERION_WEIGHT.ERRD_REAL_ADV = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRD_REAL_CLF = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRD_REAL_QUAL = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRD_FAKE_ADV = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRD_FAKE_CLF = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRG_ADV = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRG_CLF = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRG_QUAL = 1.0
_C.TRAIN.CRITERION_WEIGHT.ERRG_CONT = 1.0

_C.MODEL = CN()
_C.MODEL.LATENT_DIM = 100
_C.MODEL.INCEPTION_DIMS = 2048
_C.MODEL.EVALUATOR = 'IQT'

_C.MODEL.BACKBONE = CN()
_C.MODEL.BACKBONE.NAME = 'InceptionResNetV2'
_C.MODEL.BACKBONE.FEAT_LEVEL = 'low'
_C.MODEL.BACKBONE.FIXED = True

_C.MODEL.TRANSFORMER = CN()
_C.MODEL.TRANSFORMER.TRANSFORMER_LAYERS = 1
_C.MODEL.TRANSFORMER.TRANSFORMER_DIM = 128
_C.MODEL.TRANSFORMER.MHA_NUM_HEADS = 4
_C.MODEL.TRANSFORMER.FEAT_DIM = 1024
_C.MODEL.TRANSFORMER.HEAD_DIM = 128

cfg = _C


def get_cfg_defaults():
    """Get a yacs CfgNode object with default values for my_project."""
    # Return a clone so that the defaults will not be altered
    # This is for the "local variable" use pattern
    return _C.clone()

# Alternatively, provide a way to import the defaults as
# a global singleton:
# cfg = _C  # users can `from config import cfg`
